const RULES = [
  ['Cameras & Photography', /\b(camera|photography|lens|tripod|dslr|mirrorless|gopro|drone|camcorder)\b/i],
  ['TV & Video', /\b(television|\btv\b|projector|streaming\s?device|home\s?theater|soundbar)\b/i],
  ['Smart Home & Wearables', /\b(smart\s?home|smartwatch|wearable|fitness\s?tracker|alexa|google\s?home|home\s?automation)\b/i],
  ['Gaming', /\b(gaming|playstation|xbox|nintendo|game\s?console|gaming\s?(pc|chair|mouse|headset))\b/i],
  ['Coffee & Tea', /\b(coffee|tea\s?(leaf|bag|shop)|espresso|barista|matcha|herbal\s?tea|loose\s?leaf)\b/i],
  ['Wine & Spirits', /\b(wine|spirits?|whiskey|whisky|vodka|gin\b|rum\b|tequila|beer|brewery|distillery|champagne|liquor)\b/i],
  ['Specialty & Gourmet', /\b(gourmet|artisan(al)?\s?food|organic\s?food|specialty\s?food|truffle|caviar|saffron)\b/i],
  ['Food & Snacks', /\b(food|snack|chocolate|candy|confection|grocer|spice|sauce|jam|cookie|bakery|honey)\b/i],
  ['Board & Card Games', /\b(board\s?games?|card\s?games?|chess|monopoly|tabletop\s?games?|trading\s?card)\b/i],
  ['Video Games', /\b(video\s?games?|game\s?cartridge|switch\s?game|ps[45]\s?game|xbox\s?game)\b/i],
  ['Hobbies & Musical Instruments', /\b(hobby|hobbies|musical\s?instruments?|guitars?|piano|drums?|violin|model\s?(kit|airplane|train)|rc\s?(car|model)|cosplay)\b/i],
  ['Toys', /\b(toys?|stuffed\s?animal|plush|dolls?|action\s?figures?|lego|jigsaw\s?puzzle|kids?\s?play)\b/i],
  ['Books', /\b(books?\b|ebook|audiobook|novel|textbook|comic\s?book|magazine|self-?published)\b/i],
  ['Music & Movies', /\b(music\s?album|vinyl\s?record|\bcd\b|\bdvd\b|blu-?ray|movies?|films?)\b/i],
  ['Art Supplies', /\b(art\s?supplies?|painting\s?supply|canvas|brushes?|easel|sketchbook|charcoal|acrylic\s?paints?|watercolors?|pastels?)\b/i],
  ['Sewing & Knitting', /\b(sewing|knitting|crochet|yarn|fabric|quilting|embroidery|cross\s?stitch|sewing\s?machine)\b/i],
  ['Handmade & Crafts', /\b(handmade|crafts?|diy|artisan(al)?|pottery|sculpture|maker|woodworking|leather\s?craft)\b/i],
  ['Office & Stationery', /\b(office\s?supplies?|stationery|pens?\b|notebooks?|desk\s?supplies|planner|paper\s?products|sticky\s?note)\b/i],
  ['Auto Parts & Accessories', /\b(auto\s?parts?|car\s?(parts|accessor|care)|vehicle\s?(parts|accessor)|tires?|truck\s?parts?|automotive)\b/i],
  ['Motorcycle', /\b(motorcycle|motorbike|biker\s?gear|atv\b|scooter|moped)\b/i],
  ['Power Tools', /\b(power\s?tools?|drills?|circular\s?saws?|grinders?|sanders?|impact\s?drivers?|jigsaws?|nail\s?guns?)\b/i],
  ['Hand Tools', /\b(hand\s?tools?|hammers?|screwdrivers?|wrenches?|pliers|toolboxe?s?|socket\s?sets?)\b/i],
  ['Building Materials', /\b(building\s?materials?|lumber|drywall|cement|tiles?\s?(floor|wall)|paint\s?supplies|insulation)\b/i],
  ['Industrial & Wholesale', /\b(industrial|wholesale|b2b|manufacturing|commercial\s?supply|surplus|bulk\s?supply)\b/i],
  ['Software & Digital', /\b(software|saas|app\s?(store|download)|plugin|theme|template|digital\s?download|subscription\s?service)\b/i],
  ['Party & Celebration', /\b(party\s?(supply|decor|favor|decoration)|celebrations?|weddings?|wedding\s?(decor|favor|decoration)|birthday\s?(party|supply|decoration)|balloons?|gift\s?wrap|decorations?)\b/i],
  ['Apparel & Clothing', /\b(apparel|fashion|clothing|dress(es)?|streetwear|activewear|denim|jeans|t-?shirts?|hoodies?|jackets?|costumes?|outerwear|menswear|womens?wear|club\s?wear)\b/i],
  ['Services', /\b(consulting|coaching|agency|services?\b)\b/i],
];

module.exports = { RULES };
