const RULES = [
  ['Outdoor Furniture', /\b(outdoor\s?(furniture|seating|sofa|sectional|cushion|umbrella)|patio\s?(furniture|set|chair|table|umbrella))\b/i],
  ['Pet Food & Treats', /\b(pet\s?food|dog\s?food|cat\s?food|pet\s?treats|dog\s?treats|fish\s?food|bird\s?food|raw\s?dog\s?food)\b/i],
  ['Pet Supplies & Accessories', /\b(pet|dog|cat|puppy|kitten|aquarium|leash|kennel|veterinary|cat\s?litter|pet\s?(toy|bed|carrier|grooming))\b/i],
  ['Baby & Kids Clothing', /\b(baby\s?clothing|kids?\s?(clothing|apparel|wear)|childrens?\s?clothing|infant\s?wear)\b/i],
  ['Baby & Nursery', /\b(baby|infant|toddler|newborn|nursery|stroller|diaper|crib|maternity|baby\s?gear)\b/i],
  ['CBD & Cannabis', /\b(cbd|cannabis|hemp\s?oil|thc|marijuana|kratom|delta-?\s?8|delta-?\s?9)\b/i],
  ['Vape & Tobacco', /\b(vape|vaping|e-?cigarette|e-?juice|e-?liquid|tobacco|cigar|hookah|shisha)\b/i],
  ['Adult & Lifestyle', /\b(adult\s?toy|sex\s?toy|erotic|intimacy\s?product|lubricant|fetish)\b/i],
  ['Skincare', /\b(skincare|skin\s?care|moisturi[sz]er|serum|cleanser|exfoliat|toner|face\s?(cream|mask)|anti-?aging)\b/i],
  ['Makeup & Cosmetics', /\b(makeup|cosmetic|lipstick|mascara|foundation|eyeshadow|concealer|blush|nail\s?polish)\b/i],
  ['Haircare', /\b(haircare|hair\s?care|shampoo|conditioner|hair\s?(oil|treatment|extension|color|dye)|hairbrush)\b/i],
  ['Fragrance', /\b(fragrance|perfume|cologne|eau\s?de\s?parfum|eau\s?de\s?toilette)\b/i],
  ['Bath & Body', /\b(bath\s?(salt|bomb|soak)|bath\s?(and|&)\s?body|body\s?(care|wash|lotion|scrub|butter|oil|products?)|soap\s?bars?|bar\s?soaps?|handmade\s?soaps?)\b/i],
  ['Vitamins & Supplements', /\b(vitamins?|supplements?|dietary\s?supplements?|protein\s?powder|nutraceutical|nootropic|amino\s?acid|collagen)\b/i],
  ['Medical & Pharmacy', /\b(pharmacy|medical\s?(supply|equipment|device)|prescription|medication|first\s?aid|orthopedic)\b/i],
  ['Natural & Herbal', /\b(herbal|natural\s?(remedy|product|pharmacy)|essential\s?oil|aromatherapy|holistic|adaptogen)\b/i],
  ['Footwear', /\b(footwear|shoes?|sneakers?|boots?|sandals?|heels?|slippers?|loafers?)\b/i],
  ['Lingerie & Swimwear', /\b(lingerie|underwear|bra\b|panty|panties|swimwear|bikini|swim\s?suit|shapewear)\b/i],
  ['Bags & Luggage', /\b(handbags?|backpacks?|luggage|suitcases?|tote\s?bags?|wallets?|purses?|crossbody|duffels?|messenger\s?bags?)\b/i],
  ['Eyewear', /\b(eyewear|sunglasses|eyeglasses|reading\s?glasses|prescription\s?glasses|optical)\b/i],
  ['Jewelry', /\b(jewel(ry|lery)|necklace|earring|bracelet|gemstone|diamond|engagement\s?ring)\b/i],
  ['Watches', /\b(watches?|wristwatch(es)?|timepieces?|smart\s?watch(es)?|smartwatch(es)?)\b/i],
  ['Furniture', /\b(furniture|sofa|couch|chair|table|desk|cabinet|bookshelf|dresser|wardrobe|nightstand|bed\s?frame)\b/i],
  ['Home Decor', /\b(home\s?decor|wall\s?art|mirror|vase|sculpture|decorative|tapestry|figurine)\b/i],
  ['Kitchen & Dining', /\b(kitchen|dinnerware|cookware|cutlery|utensil|chef|cooking|bakeware|tableware)\b/i],
  ['Bedding & Bath', /\b(bedding|mattress|pillow|sheet|comforter|duvet|towel|bath\s?(robe|mat|rug)|bathroom)\b/i],
  ['Lighting', /\b(lighting|lamps?|chandelier|pendant\s?light|sconce|led\s?light|floor\s?lamp|table\s?lamp)\b/i],
  ['Appliances', /\b(appliance|refrigerator|microwave|dishwasher|vacuum|blender|mixer|air\s?fryer|coffee\s?maker)\b/i],
  ['Candles & Aromatherapy', /\b(candle|incense|aromatherapy|diffuser|wax\s?melt|reed\s?diffuser)\b/i],
  ['Garden & Plants', /\b(garden(ing)?|plants?|seeds?|landscaping|lawn|flowers?|succulent|nursery\s?plant)\b/i],
  ['Outdoor Recreation', /\b(camping|hiking|backpacking|tent|sleeping\s?bag|trekking|climbing|hunting\s?gear)\b/i],
  ['Cycling', /\b(cycling|bicycles?|bikes?|cyclists?|mountain\s?bikes?|road\s?bikes?|e-?bikes?|bike\s?(parts|accessor))\b/i],
  ['Fitness Equipment', /\b(fitness\s?(equipment|gear)|gym\s?equipment|treadmills?|dumbbells?|barbells?|yoga\s?(mats?|gear)|kettlebells?|resistance\s?band)\b/i],
  ['Hunting & Shooting', /\b(hunting|firearm|gun|rifle|shooting|archery|crossbow|ammunition)\b/i],
  ['Water Sports', /\b(surfing|surfboards?|kayaks?|paddleboards?|diving|snorkel|fishing|rowing|sup\b|wakeboard|jetski)\b/i],
  ['Sporting Goods', /\b(sporting\s?goods?|sport\s?equipment|athletic\s?(gear|equipment)|football|basketball|baseball|soccer|tennis|skiing|skateboard|skating)\b/i],
  ['Mobile Phones & Accessories', /\b(mobile\s?phones?|smartphones?|cell\s?phones?|phone\s?(case|accessor|charger|cover)|airpods|earpods)\b/i],
  ['Computers & Tablets', /\b(computer|laptop|desktop|tablet|ipad|chromebook|macbook|monitor|keyboard|mouse\s?pad)\b/i],
  ['Audio & Headphones', /\b(headphones?|earbuds?|speakers?|audio\s?(equipment|gear)|hifi|amplifier|microphone|turntable)\b/i],
];

module.exports = { RULES };
