const CATEGORIES = [
  'Apparel & Clothing', 'Footwear', 'Lingerie & Swimwear', 'Bags & Luggage',
  'Eyewear', 'Jewelry', 'Watches',
  'Skincare', 'Makeup & Cosmetics', 'Haircare', 'Fragrance', 'Bath & Body',
  'Vitamins & Supplements', 'Medical & Pharmacy', 'Natural & Herbal',
  'Furniture', 'Outdoor Furniture', 'Home Decor', 'Kitchen & Dining',
  'Bedding & Bath', 'Lighting', 'Appliances', 'Candles & Aromatherapy',
  'Garden & Plants',
  'Sporting Goods', 'Outdoor Recreation', 'Cycling', 'Fitness Equipment',
  'Hunting & Shooting', 'Water Sports',
  'Computers & Tablets', 'Mobile Phones & Accessories', 'Audio & Headphones',
  'Cameras & Photography', 'TV & Video', 'Smart Home & Wearables', 'Gaming',
  'Food & Snacks', 'Coffee & Tea', 'Wine & Spirits', 'Specialty & Gourmet',
  'Pet Food & Treats', 'Pet Supplies & Accessories',
  'Toys', 'Board & Card Games', 'Video Games', 'Hobbies & Musical Instruments',
  'Baby & Nursery', 'Baby & Kids Clothing',
  'Books', 'Music & Movies',
  'Art Supplies', 'Handmade & Crafts', 'Sewing & Knitting',
  'Office & Stationery',
  'Auto Parts & Accessories', 'Motorcycle',
  'Power Tools', 'Hand Tools', 'Building Materials',
  'Industrial & Wholesale', 'Software & Digital',
  'CBD & Cannabis', 'Vape & Tobacco', 'Adult & Lifestyle', 'Party & Celebration',
  'Services', 'Other',
];

module.exports = { CATEGORIES };
